{
 "title": "CLCPlus Usage",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Requests by User",
   "type": "bargauge",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "rawSql": "select\r\n\tc.first_name || ' ' || c.last_name ,\r\n\tcount(*)\r\nfrom\r\n\tcustomer.service_orders so ,\r\n\tcustomer.services s,\r\n\tcustomer.customer c\r\nwhere\r\n\ts.service_id = so.service_id\r\n\tand so.customer_id = c.customer_id\r\n\tand status is not null\r\n\tand so.order_received >'2021-04-26 13:10'\r\ngroup by\r\n\t1\r\norder by\r\n\t2 desc;\r\n"
    }
   ]
  },
  {
   "title": "Requests by Service",
   "type": "gauge",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "select\r\n\ts.service_name,\r\n\tcount(*)\r\nfrom\r\n\tcustomer.service_orders so ,\r\n\tcustomer.services s\r\nwhere\r\n\ts.service_id = so.service_id\r\n\tand so.order_received >'2021-04-26 13:10'\r\ngroup by\r\n\t1\r\norder by\r\n\t2 desc;"
    }
   ]
  },
  {
   "title": "Mean duration for successful orders",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "select\r\n\ts.service_name,\r\n\tavg(extract(epoch from (so.order_stopped - so.order_received ))/ 60.0) as duration\r\nfrom\r\n\tcustomer.service_orders so ,\r\n\tcustomer.services s\r\nwhere\r\n\ts.service_id = so.service_id\r\n\tand so.success is true\r\n\tand (so.order_stopped - so.order_started ) is not null\r\n\tand order_received > '2021-04-26 13:10'\r\n  group by\r\n\t1\r\norder by\r\n\t1;"
    }
   ]
  },
  {
   "title": "Current parallel executions of services",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "parallel" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "select\r\n\ts.service_name,\r\n\tcount(*) as anzahl\r\nfrom\r\n\tcustomer.service_orders so, customer.services s \r\nwhere\r\n\tstatus in ('RUNNING')\r\n\tand so.service_id = s.service_id\r\n\tand order_received > '2021-04-26 13:10'\r\ngroup by\r\n\t1"
    }
   ]
  },
  {
   "title": "ETA in days for current orders",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "d" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "select\r\n\ts.service_name,\r\n\tavg(extract(epoch from (so.order_stopped - so.order_received ))/ (60.0 * 60.0 * 24)) * daten.anzahl / daten_parallel.anzahl_parallel as eta\r\nfrom\r\n\tcustomer.service_orders so ,\r\n\tcustomer.services s,\r\n\t(\r\n\tselect\r\n\t\tservice_id,\r\n\t\tcount(*) as anzahl\r\n\tfrom\r\n\t\tcustomer.service_orders so\r\n\twhere\r\n\t\tstatus in ('RECEIVED', 'QUEUED')\r\n\t\tand order_received > '2021-04-26 13:10'\r\n\tgroup by\r\n\t\t1) as daten,\r\n\t(\r\n\tselect\r\n\t\tservice_id,\r\n\t\tcount(*) as anzahl_parallel\r\n\tfrom\r\n\t\tcustomer.service_orders so\r\n\twhere\r\n\t\tstatus in ('RUNNING')\r\n\t\t\tand order_received > '2021-04-26 13:10'\r\n\t\tgroup by\r\n\t\t\t1) as daten_parallel\r\nwhere\r\n\ts.service_id = so.service_id\r\n\tand daten_parallel.service_id = so.service_id\r\n\tand daten.service_id = so.service_id\r\n\tand so.success is true\r\n\tand (so.order_stopped - so.order_started ) is not null\r\n\tand order_received > '2021-04-26 13:10'\r\ngroup by\r\n\ts.service_name,\r\n\tdaten.anzahl,\r\n\tdaten_parallel.anzahl_parallel\r\norder by\r\n\t1;"
    }
   ]
  },
  {
   "title": "Service Status",
   "type": "michaeldmoore-multistat-panel",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 37 },
   "targets": [
    {
     "rawSql": "select\r\n  s.service_name,\r\n\tso.status ,\r\n\tcount(*)\r\nfrom\r\n\tcustomer.service_orders so ,\r\n\tcustomer.services s\r\nwhere\r\n\ts.service_id = so.service_id\r\n\tand status is not null\r\n\tand so.order_received >'2021-04-26 13:10'\r\n\tand status not in ('FAILED','INVALID','SUCCESS')\r\n\tand current_timestamp - order_received <'10 days'::interval\r\ngroup by\r\n\t1,2\r\norder by\r\n\t1 desc;"
    }
   ]
  },
  {
   "title": "Service Status",
   "type": "michaeldmoore-multistat-panel",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 49 },
   "targets": [
    {
     "rawSql": "select\r\n  s.service_name,\r\n\tso.status ,\r\n\tcount(*)\r\nfrom\r\n\tcustomer.service_orders so ,\r\n\tcustomer.services s\r\nwhere\r\n\ts.service_id = so.service_id\r\n\tand status is not null\r\n\tand so.order_received >'2021-04-26 13:10'\r\n\tand status in ('FAILED','INVALID','SUCCESS')\r\ngroup by\r\n\t1,2\r\norder by\r\n\t1 desc;"
    }
   ]
  },
  {
   "title": "Last 100 Failed Services",
   "type": "table",
   "description": "\n",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 61 },
   "targets": [
    {
     "rawSql": "select\r\n\t*\r\nfrom\r\n\tcustomer.service_orders so\r\nwhere\r\n\t--order_received > '2021-04-26 15:00:00'\r\n\tstatus = 'FAILED'\r\n\torder by order_received desc\r\n\tlimit 100;"
    }
   ]
  }
 ]
}